### ISSUE TITLE
Не проводятся платежи по тестовым картам

### ISSUE THREAD

**Issue by xurc** [safecrow/docs-apiv3#14]
Не проводятся платежи по тестовым картам, указанным в документации. После ввода данных появляется страница ожидания, которое никогда не заканчивается.

![image](https://user-images.githubusercontent.com/7814098/47707601-4d222800-dc3d-11e8-99e8-3527b52db009.png)

**Comment by StanislavNaumov** [comment]
Это на стороне мандарина какие то косяки, мы им сообщили, конечно, но пока что никакой тестовый терминал не работает.
